package:
  name: eigen3
  version: "3.2.5"

source:
  fn: eigen3-3.2.5.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2

requirements:
  build:
    - cmake    [not win]

test:
  files:
    - test.cc  [not win]

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
