package:
  name: pcl
  version: 1.7.2

source:
  fn:  pcl-1.7.2.tar.gz
  url: https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz
  patches:
    - supervoxel.patch      [win]
    - gp3_surface.patch     [win]
    - mls_smoothing.patch   [win]

requirements:
  build:
    - cmake
    - eigen3
    - flann
    - boost    <1.56.0
    - libpng                [unix]
    - zlib                  [unix]
    - pkg-config            [unix]
  run:
    - eigen3
    - flann
    - boost    <1.56.0
    - libpng                [unix]
    - zlib                  [unix]

about:
  home: http://pointclouds.org/
  license: BSD
