package:
  name: python-pcl
  version: 0.2

source:
  git_url: https://github.com/strawlab/python-pcl.git
  git_rev: f17c686b63fe16a39ba612124def14dda2762525
  patches:
    - ext_args_win.patch                      [win]
    - dlls.patch                              [win]
    - ext_args_osx.patch                      [osx]

build:
  number: 2                                   [win]
  number: 1                                   [osx]
  number: 2                                   [linux]
  has_prefix_files:                           [win]
    - Lib/site-packages/pcl/__init__.py       [win]

requirements:
  build:
    - python
    - cython        <0.22
    - numpy
    - pkg-config
    - pcl
    - gcc                                     [linux]
  run:
    - python
    - numpy
    - pcl
    - libgcc                                  [linux]

test:
  imports:
    - pcl

about:
  home: https://github.com/strawlab/python-pcl
  license: BSD
