package:
  name: python-pcl
  version: 1.0

source:
    git_url: https://github.com/strawlab/python-pcl.git
    git_rev: f17c686b63fe16a39ba612124def14dda2762525
    patches:
      - ext_args.patch                    [win]
      - dlls.patch                        [win]

build:
  has_prefix_files:
    - Lib/site-packages/pcl/__init__.py   [win]

requirements:
  build:
    - python
    - cython
    - numpy
    - pkg-config
    - pcl
  run:
    - python
    - numpy
    - pcl

test:
  imports:
    - pcl

about:
  home: https://github.com/strawlab/python-pcl
  license: BSD
