package:
  name: gtest
  version: 1.7.0

source:
  fn:  gtest-1.7.0.zip
  url: https://googletest.googlecode.com/files/gtest-1.7.0.zip

requirements:
  build:
    - cmake

about:
  home: http://www.cs.ubc.ca/research/flann/
  license: BSD
