package:
  name: boost
  version: 1.55.0

source:
  fn:  boost_1_55_0-msvc-9.0-64.exe                                                                        [win64]
  url: http://downloads.sourceforge.net/project/boost/boost-binaries/1.55.0/boost_1_55_0-msvc-9.0-64.exe   [win64]
  fn:  boost_1_55_0.tar.bz2                                                                                [unix]
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2                       [unix]
  patches:
    - patch-atomic.diff    [osx]

build:
  number: 2

requirements:
  build:	
    - python     <3
    - icu                  [unix]
    - bzip2                [unix]
    - libpython            [win]

  run:
    - python     <3
    - icu                  [unix]

about:
  home: http://www.boost.org/
  license: Boost-1.0
