package:
  name: boost
  version: 1.55.0

source:
  fn: boost_1_55_0-msvc-10.0-64.exe                                                                        [win64]
  url: http://downloads.sourceforge.net/project/boost/boost-binaries/1.55.0/boost_1_55_0-msvc-10.0-64.exe  [win64]
  
requirements:
  run:	
    - python <3

about:
  home: http://www.boost.org/
  license: Boost-1.0
