package:
  name: cmake
  version: 3.3.0

source:
  fn:  cmake-3.3.0-win32-x86.zip                                     [win]
  url: http://www.cmake.org/files/v3.3/cmake-3.3.0-win32-x86.zip     [win]

test:
  commands:
    - cmake --version

about:
  home: http://www.cmake.org/
  license: BSD
